apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-redis
  labels:
    app: {{ .Release.Name }}
    component: queue
spec:
  serviceName: "{{ .Release.Name }}-redis"
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}
      component: queue
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
        component: queue
    spec:
      containers:
        - name: redis
          image: redis:7-alpine
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: data
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: {{ .Values.redis.storageSize }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-redis
spec:
  ports:
    - port: 6379
  clusterIP: None
  selector:
    app: {{ .Release.Name }}
    component: queue
